server:
  tomcat:
    uri-encoding: UTF-8
    threads:
      max: 1000
      min-spare: 30
  port: 8099
  servlet:
    session:
      cookie:
        http-only: true

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DATASOURCE.IP:ip}:3306/admin-ease?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B9&allowPublicKeyRetrieval=true&allowMultiQueries=true&rewriteBatchedStatements=true
    username: root
    password: ${DATASOURCE.PASSWORD:password}
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      pool-name: HikariCP-Primary

knife4j:
  enable: true

decorator:
  datasource:
    p6spy:
      # 日志格式
      log-format: "\ntime:%(executionTime) || sql:%(sql)\n"
      # 自定义日志类
      logging: custom
      custom-appender-class: com.ease.admin.common.p6spy.StdoutLogger

logging:
  config: classpath:logback-dev.xml
